shellcheck'd and multi stage dockerfile

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,16 +1,24 @@
 #!/bin/bash
 
-PROGNAME=$(basename $0)
-RELEASE="Revision 1.0.4"
-AUTHOR="(c) 2020 Paul Bargewell (paul.bargewell@opusvl.com)"
-LICENSE="SPDX-License-Identifier: AGPL-3.0-or-later"
+# PROGNAME=$(basename $0)
+# RELEASE="Revision 1.0.5"
+# AUTHOR="Paul Bargewell <paul.bargewell@opusvl.com>"
+# COPYTRIGHT="Copyright 2021, Opus Vision Limited T/A OpusVL"
+# LICENSE="SPDX-License-Identifier: AGPL-3.0-or-later"
+
+source .env
 
 if [[ ! -f ".env" ]]; then
   echo "ERROR: You need to create a .env file first (see .env.example)."
   exit 1
 fi
 
-source .env
+SUDO=$(which sudo)
+
+if [[ -z "${SUDO}" ]]; then
+  echo "We need to elevate privileges using 'sudo' which can't be found."
+  exit 1
+fi
 
 readonly PYTHON_JINJA2="import os;
 import sys;
@@ -25,7 +33,8 @@ sys.stdout.write(
 function render() {
   if [[ -f "$1" ]]; then
     echo "Templating: $1"
-    cat "$1" | python -c "${PYTHON_JINJA2}" > `echo "$1" | sed 's/\.template//gi'`
+    # cat "$1" | python -c "${PYTHON_JINJA2}" > "${1//\.template/}"
+    < "$1" python -c "${PYTHON_JINJA2}" > "${1//\.template/}"
   else
     echo "$1 File not found."
     exit 1
@@ -34,19 +43,33 @@ function render() {
 
 # Render the templates first
 
-for t in prosody/etc/conf.d/modules.cfg.template.lua prosody/etc/ldap-roster.template.py prosody/etc/prosody.cfg.template.lua prosody/etc/conf.d/extra.cfg.template.lua prosody/etc/conf.d/logging.cfg.template.lua prosody/etc/vhost.d/vhost.cfg.template.lua rest/create_realm.template.json rest/create_ldap.template.json nginx/nginx.template.conf nginx/deploy/10-prosody-certs.template
+TEMPLATES=(prosody/etc/conf.d/modules.cfg.template.lua 
+  prosody/etc/ldap-roster.template.py 
+  prosody/etc/prosody.cfg.template.lua 
+  prosody/etc/conf.d/extra.cfg.template.lua 
+  prosody/etc/conf.d/logging.cfg.template.lua 
+  prosody/etc/vhost.d/vhost.cfg.template.lua 
+  rest/create_realm.template.json 
+  rest/create_ldap.template.json 
+  nginx/nginx.template.conf 
+  nginx/deploy/10-prosody-certs.template
+)
+
+for TEMPLATE in "${TEMPLATES[@]}"
 do
-  render $t
+  render "$TEMPLATE"
 done
 
 # Deliver template to Nginx
 
-sudo cp nginx/deploy/{10-prosody-certs,20-reload-nginx} /etc/letsencrypt/renewal-hooks/deploy/
+${SUDO} cp nginx/deploy/{10-prosody-certs,20-reload-nginx} /etc/letsencrypt/renewal-hooks/deploy/
 
-sudo cp ./nginx/nginx.conf /etc/nginx/conf.d/${SERIAL}.conf && \
-  sudo nginx -t && sudo systemctl reload nginx
+${SUDO} cp ./nginx/nginx.conf "/etc/nginx/conf.d/${SERIAL}.conf"
 
-if [[ $? -ne 0 ]]; then
+TEST=(nginx -t)
+RELOAD=(systemctl reload nginx)
+  
+if [[ $(${SUDO} "${TEST[@]}") -ne 0 ]] && [[ $(${SUDO} "${RELOAD[@]}") -ne 0 ]]; then
   echo "NGINX: Failure to reload."
   exit 1
 fi
diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,15 +1,24 @@
 #!/bin/bash
 
-PROGNAME=$(basename $0)
-RELEASE="Revision 1.0.5"
-AUTHOR="(c) 2020 Paul Bargewell (paul.bargewell@opusvl.com)"
-LICENSE="SPDX-License-Identifier: AGPL-3.0-or-later"
+# PROGNAME=$(basename $0)
+# RELEASE="Revision 1.0.6"
+# AUTHOR="Paul Bargewell <paul.bargewell@opusvl.com>"
+# COPYTRIGHT="Copyright 2021, Opus Vision Limited T/A OpusVL"
+# LICENSE="SPDX-License-Identifier: AGPL-3.0-or-later"
 
 source ./configure
 
+DOCKER_COMPOSE=$(which docker-compose)
+CURL=$(which curl)
+
+if [[ -z "${DOCKER_COMPOSE}" ]] || [[ -z "${CURL}" ]]; then
+    echo "Missing prerequisite 'docker-compose' or 'curl'"
+    exit 1
+fi
+
 # This will bring up keycloak, slapd and db
 
-docker-compose up -d keycloak
+${DOCKER_COMPOSE} up -d keycloak
 
 # Use the Keycloak API to create the realm and LDAP component
 
@@ -18,52 +27,65 @@ echo "Configuring KEYCLOAK"
 # Wait until the keycloak instance is responding
 n=0 # 6 retries every 10s
 until [ "$n" -ge 6 ]; do
-  curl --fail --silent -o /dev/null http://127.0.0.1:${PORTBASE}80/auth/realms/master/.well-known/openid-configuration && break
-  if [[ $? -ne 0 ]]; then
-    echo "KEYCLOAK: Retrying in 10 seconds."
-    n=$((n+1))
-    sleep 10
-  fi
+    ARGS=(--fail
+        --silent
+        -o /dev/null
+        "http://127.0.0.1:${PORTBASE}80/auth/realms/master/.well-known/openid-configuration"
+    )
+    if [[ $(${CURL} "${ARGS[@]}") -ne 0 ]]; then
+        echo "KEYCLOAK: Retrying in 10 seconds."
+        n=$((n+1))
+        sleep 10
+    else
+        break
+    fi
 done
 
-TOKEN=$(curl --request POST \
-  --url http://127.0.0.1:${PORTBASE}80/auth/realms/master/protocol/openid-connect/token \
-  --header 'content-type: application/x-www-form-urlencoded' \
-  --data grant_type=password \
-  --data client_id=admin-cli \
-  --data username=admin \
-  --data password=${KEYCLOAK_PASSWORD} \
-  --silent --fail | jq -r '.access_token')
+ARGS=(--request POST
+    --url "http://127.0.0.1:${PORTBASE}80/auth/realms/master/protocol/openid-connect/token"
+    --header "content-type: application/x-www-form-urlencoded"
+    --data grant_type=password
+    --data client_id=admin-cli
+    --data username=admin
+    --data password="${KEYCLOAK_PASSWORD}"
+    --silent --fail
+)
 
-if [[ $? -ne 0 ]] || [[ -z "${TOKEN}" ]]; then
+if [[ $(TOKEN=${CURL} "${ARGS[@]}" | jq -r ".access_token") -ne 0 ]]; then
     echo "KEYCLOAK: Authentication Failed."
     exit 1
 else
+    if  [[ -z "${TOKEN}" ]]; then
+        echo "KEYCLOAK: Invalid token returned."
+        exit 1
+    fi
     echo "KEYCLOAK: Authentication Success."
 fi
 
-curl --request POST \
-  --url http://127.0.0.1:${PORTBASE}80/auth/admin/realms \
-  --header "authorization: bearer ${TOKEN}" \
-  --header 'content-type: application/json' \
-  --silent --fail \
-  --data @rest/create_realm.json
+ARGS=(--request POST
+    --url "http://127.0.0.1:${PORTBASE}80/auth/admin/realms"
+    --header "authorization: bearer ${TOKEN}"
+    --header "content-type: application/json"
+    --silent --fail
+    --data @rest/create_realm.json
+)
 
-if [[ $? -ne 0 ]]; then
+if [[ $(${CURL} "${ARGS[@]}") -ne 0 ]]; then
     echo "KEYCLOAK: Unable to create REALM (Does it already exist?)."
     exit 1
 else
     echo "KEYCLOAK: REALM ${HOST} created."
 fi
 
-curl --request POST \
-  --url http://127.0.0.1:${PORTBASE}80/auth/admin/realms/${HOST}/components \
-  --header "authorization: bearer ${TOKEN}" \
-  --header 'content-type: application/json' \
-  --silent --fail \
-  --data @rest/create_ldap.json 
+ARGS=(--request POST
+    --url "http://127.0.0.1:${PORTBASE}80/auth/admin/realms/${HOST}/components"
+    --header "authorization: bearer ${TOKEN}"
+    --header "content-type: application/json"
+    --silent --fail
+    --data @rest/create_ldap.json
+)
 
-if [[ $? -ne 0 ]]; then
+if [[ $(${CURL} "${ARGS[@]}") -ne 0 ]]; then
     echo "KEYCLOAK: Unable to create LDAP component."
     exit 1
 else
@@ -72,34 +94,38 @@ fi
 
 # To get this far implies keycloak is running which means the database is ready.
 
-sudo mkdir -p ${CONTAINER_VOLUME}/${SERIAL}/{prosody,logs}
-sudo chmod g+rw,o+rw ${CONTAINER_VOLUME}/${SERIAL}/{prosody,logs} -R
-sudo chown 1000 ${CONTAINER_VOLUME}/${SERIAL}/{prosody,logs} -R
-sudo chgrp 1000 ${CONTAINER_VOLUME}/${SERIAL}/{prosody,logs} -R
+sudo mkdir -p "${CONTAINER_VOLUME}/${SERIAL}/{prosody,logs}"
+sudo chmod g+rw,o+rw "${CONTAINER_VOLUME}/${SERIAL}/{prosody,logs}" -R
+sudo chown 1000 "${CONTAINER_VOLUME}/${SERIAL}/{prosody,logs}" -R
+sudo chgrp 1000 "${CONTAINER_VOLUME}/${SERIAL}/{prosody,logs}" -R
 
 # Start all the other containers
 echo "Starting All Containers."
-docker-compose up -d
+${DOCKER_COMPOSE} up -d
 # Resolve the Movim permission error by starting movim again
 echo "Taking a breath... back in 10s"
 sleep 10
-docker-compose up -d movim
+${DOCKER_COMPOSE} up -d movim
 
 echo "Configuring MOVIM"
 
 # Wait until the keycloak instance is responding
 n=0 # 6 retries every 10s
 until [ "$n" -ge 6 ]; do
-  curl --fail --silent -o /dev/null http://127.0.0.1:${PORTBASE}81/?login && break
-  if [[ $? -ne 0 ]]; then
-    echo "MOVIM: Retrying in 10 seconds."
-    docker-compose up -d movim
-    n=$((n+1))
-    sleep 10
-  fi
+    ARGS=(--fail 
+        --silent 
+        -o /dev/null 
+        "http://127.0.0.1:${PORTBASE}81/?login"
+    )
+    if [[ $(${CURL} "${ARGS[@]}") -ne 0 ]]; then
+        echo "MOVIM: Retrying in 10 seconds."
+        ${DOCKER_COMPOSE} up -d movim
+        n=$((n+1))
+        sleep 10
+    fi
 done
 
 echo "update configuration set xmppdomain='${HOST}.${DOMAIN}', xmppdescription='${LDAP_ORGANISATION}', chatonly=true where username='admin';" | \
-  docker-compose exec -T db psql -U movim -d movim
+${DOCKER_COMPOSE} exec -T db psql -U movim -d movim
 
 echo "Done."
